version: "3.9"

services:
  loadbalancer:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "50MB"

  api01: &api01
    container_name: api01
    hostname: api01
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./:/src
    ports:
      - "81:80"
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "175MB"

  api02:
    <<: *api01
    container_name: api02
    hostname: api02
    ports:
      - "82:80"

  db:
    image: postgres:14.1-alpine
    command: postgres -c config_file="/etc/database.conf"
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
        - '5432:5432'
    volumes:
        - ./script.sql:/docker-entrypoint-initdb.d/init.sql
        - ./database.conf:/etc/database.conf
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: "150MB"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d rinha_backend" ]
      interval: 3s
      timeout: 1s
      retries: 10
networks:
  default:
    driver: bridge
    name: rinha-2024-q1